### PR TITLE
Add USDT in the UI

### PR DESCRIPTION
**Pull request by kevinuma**
Similar to https://github.com/across-protocol/frontend-v2/pull/218

### CODE REVIEW

**Comment by daywiss** [comment]
unlike 218, this hasnt been enabled on chain, hopefully that is expected, but we should not merge this until that is verified

**Comment by Tulun** [comment]
Yeah seems gtg once the other stuff is done.

**Review by mrice32 — APPROVED** [review]
LGTM! Addresses look right!

**Review by daywiss — COMMENTED** [review]
can you re-request me once our contracts are upgraded and ill check this against a script that pulls it down from on chain

**Pull request merged**
