### PR TITLE
fix: improve table layout

### PR DESCRIPTION
**Pull request by amateima**
This PR brings a couple of UI improvements:

- implement mobile layout according to Figma design
- add custom table horizontal scrollbars
- add Filled column on mobile
- adjust colours & spacing where necessary

**Result**

Screenshot 2022-05-23 at 13 53 42
Screenshot 2022-05-23 at 13 54 11
Screenshot 2022-05-23 at 13 57 53
Screenshot 2022-05-23 at 13 58 16

### CODE REVIEW

**Review by daywiss — APPROVED** [review]
looks great

**Comment by daywiss** [comment]
im seeing some logs, which are probably coming from teh client so not related to these change 
image

**Comment by amateima** [comment]
> im seeing some logs, which are probably coming from teh client so not related to these change image

@daywiss 
Error: `couldn't fill deposit on chain 137` is interesting. I suspect that the Spoke Pools addresses are not in sync anymore. The coresponding Deposit event on source chain was not found for a particular Fill event

**Comment by jespergisslen** [comment]
Nice!

**Pull request merged**
