### PR TITLE
fix: prevent setting across.to as referring_domain

### PR DESCRIPTION
**Pull request by dohaki**

### CODE REVIEW

**Review by amateima — APPROVED** [review]
Can I get more context for this change? How does it impact amplitude?

**Comment by dohaki** [comment]
> Can I get more context for this change? How does it impact amplitude?

On Amplitude we have some `referring_domain` values set to `across.to` when we do internal links via `<a href />`. This overrides the "real" referring_domain that we are interested in. So this PR just ignores internal links

**Review by james-a-morris — APPROVED** [review]
LGTM! Should the goerli be failing or is the error transient?

**Comment by dohaki** [comment]
> LGTM! Should the goerli be failing or is the error transient?

It was transient 👍

**Pull request merged**
