### PR TITLE
test: enable per-route capital fee config

### PR DESCRIPTION
**Pull request by james-a-morris**
This test enables a capital fee override for USDC between its Optimism <> Arbitrum route.

### CODE REVIEW

**Review by daywiss — APPROVED** [review]
lgtm

**Review by nicholaspai — CHANGES_REQUESTED** [review]
We shouldn't merge this until the relayer is set up to handle lower fees: https://github.com/across-protocol/relayer-v2/pull/452

**Review by nicholaspai — APPROVED** [review]
LGTM, but hold off on merging until we merge the rate model update at approximately the same time

**Review by mrice32 — APPROVED** [review]
LGTM!

**Pull request merged**
