### PR TITLE
fix: change formatting style for numbers

### PR DESCRIPTION
**Pull request by daywiss**
this pr is updated with a new strategy proposed by korpi:
if number is less than 1, minimum use significant digits
if greater than one use maximum fraction digits
for numbers 1000 or greater, we drop any fractional values
This seems to work well for big and small values

I think with this technique we dont need any tool tips since we both minimize what we show and show necessary decimals when numbers are really small 

new behavior
image
image

old behavior
image
image

### CODE REVIEW

**Comment by mrice32** [comment]
Screen Shot 2022-07-21 at 3 25 36 PM
Is this a problem?

**Review by mrice32 — COMMENTED** [review]
https://github.com/across-protocol/frontend-v2/pull/180#issuecomment-1191852255

**Comment by daywiss** [comment]
> Is this a problem?

I think this is a bad example because the fees actually probably are 0 since btc only has 6 decimal resolution

**Comment by mrice32** [comment]
I think it’s 8 decimal resolution.

**Review by amateima — APPROVED** [review]

**Comment by daywiss** [comment]
> I think it’s 8 decimal resolution.

Yea you are right, so it might not be 0, but try with the new configuration, it should work better @mrice32

**Pull request merged**
